### ISSUE TITLE
Dart SASS is deprecating using '/' for division

### ISSUE THREAD

**Issue by brandonbarringer** [Jakobud/poly-fluid-sizing#5]
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0
More info and automated migrator: https://sass-lang.com/d/slash-div

Can we update to use `div()` ?

**Comment by Jakobud** [comment]
Thanks for the callout. I will update this soon.

**Comment by Jakobud** [comment]
This has been addressed in https://github.com/Jakobud/poly-fluid-sizing/pull/4
